hadoop_streaming_jar: Dependencies/hadoop-streaming-3.2.1.jar
mapper_path: Elements/MapRed/mapper.py
reducer_path: Elements/MapRed/reducer.py
input_dir: /Hiraishin/input
output_dir: /Hiraishin/output
clean_hdfs: hdfs dfs -rm -r /Hiraishin/output
element_path: Dependencies/elements.json
local_output_dir: Dependencies/map_red_output
clean_directory: rm -r -f Dependencies/map_red_output/