hadoop_streaming_jar: Dependencies/hadoop-streaming-3.2.1.jar
mapper_path: Elements/MapRed/mapper.py
reducer_path: Elements/MapRed/reducer.py
input_dir: /Hiraishin/input
output_dir: /Hiraishin/output
initiate_command: hadoop dfs -rm -r /Hiraishin/output